### ISSUE TITLE
JSON-stat2 output format missing

### ISSUE THREAD

**Issue by janbrus** [PxTools/PxWebApi#102]
If I try to get output in JSON-stat version2 using "outputformat=json-stat2" i get PX output format.

Try:
https://api.scb.se/OV0104/v2beta/api/v2/tables/TAB1292/data?lang=sv&outputformat=json-stat2

It should give JSON-stat version2 output. For expected result, see :
https://pxapi2-master-px.scb.se/api/v2/tables/TAB004/data?lang=en&OutputFormat=json-stat2
or
https://data.qa.ssb.no/pxapi2-beta/api/v2/tables/09190/data?lang=no&outputformat=json-stat2

**Comment by JohannesFinsveen** [comment]
Hi Jan! 
Thank you for taking the time to report 
@petroslikidis Could it be the entry in config OutputFormats has underscore not minus?

**Comment by runejo** [comment]
I belive it was a loadbalancer issue, it works now.
