### ISSUE TITLE
Language file are not found in Docker container

### ISSUE THREAD

**Issue by likp** [PxTools/PxWebApi#240]
When running the docker container the language files seems not to be configured properly.
Only getting the language key names.

**Comment by runejo** [comment]
Can you show an example?

**Comment by likp** [comment]
If you run a new instance of the conatiner with
```bash
docker run --rm -p 8080:8080 ghcr.io/pxtools/pxwebapi:latest
```

Then if you e.g. fetching the default selection for table `TAB004` with 

```bash
curl http://localhost:8080/api/v2/tables/TAB004/data?outputFormat=json-stat2
```

You will set  that the label for the table is `Total air emissions PxcMetaTitleBy sector, contents, year PxcMetaTitleAnd greenhouse gas`. 
`PxcMetaTitleBy` and `PxcMetaTitleAnd` indicates that it can not locate the language fies in  the container

**Comment by runejo** [comment]
I see the problem, the `app.config` has the wrong path after a `dotnet publish``

```
<paxiom>
  <localization filespath="../../../wwwroot/Languages" basefile="pxlang"/>
  <grouping filespath="../../../wwwroot/Aggregations"/>
</paxiom>
```
should have been
```
<paxiom>
  <localization filespath="/wwwroot/Languages" basefile="pxlang"/>
  <grouping filespath="/wwwroot/Aggregations"/>
</paxiom>
```
I'll fix it 👍
