### ISSUE TITLE
Table labels include "PxcMetaTitleBy" and "PxcMetaTitleAnd" under /tables/{id}/metadata endpoint

### ISSUE THREAD

**Issue by rubenselander** [PxTools/PxWebApi#92]
As the title says, instead of "by"/"and" like intended, table labels include "PxcMetaTitleBy"/"PxcMetaTitleAnd" in the GET endpoint /tables/{id}/metadata. The bug is present for both languages. The bug is isolated to "/tables/{id}/metadata" endpoint and does not occur in the endpoints "/navigation/{id}", "/tables/{id}" or "/tables".

Just open "https://api.scb.se/OV0104/v2beta/api/v2/tables/TAB1292/metadata" to see the bug.

**Comment by janbrus** [comment]
The bug is also in /data:
https://api.scb.se/OV0104/v2beta/api/v2/tables/TAB1292/data?lang=en
TITLE="Agricultural enterprises PxcMetaTitleBy region, observations PxcMetaTitleAnd year";

**Comment by likp** [comment]
Closing this since it is Statistics Swedens beta site that had a miss-configuration that should be fixed now.
